apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-ibaxjnlm
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-ibaxjnlm:bc9e6d6399931bac5cc0b595e36f5cdd2498c157@sha256:79ec0e725af5a10cd2cb3204f2d033378f5352582ae888f8f7990336fa7eed33
          name: container-image
